[github]
owner="Cloumy074"
repository="friend-links"

[generation]
label="active"
sort_by_updated_time=true

[[groups]]
name="Partner (Pinned)"
description="Special place for special person."
label="ta"
[[groups]]
name="Frequently Visited"
description="Very useful websites worth bookmarking."
label="frequently-visited"
[[groups]]
name="Friends"
description="Some of my friends! Might would like to take a look?"
label="friends"
