[github]
owner="Cloumy074"
repository="friend-links"

[generation]
label="active"
sort_by_updated_time=true

[[groups]]
name="GitHub"
description="Some friends from GitHub! Might would like to take a look?"
label="github"
